const {test,expect}=require('@playwright/test');
const fs=require('node:fs');
test('capture admin baseline and membership entry point',async({page},testInfo)=>{
 const credentials=JSON.parse(fs.readFileSync(process.env.OMLMS_TEST_CREDENTIALS,'utf8'));
 const errors=[],failures=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('response',r=>{if(r.status()>=400)failures.push({url:r.url(),status:r.status()});});
 await page.goto('/wp-login.php');
 await page.locator('#user_login').fill(credentials.username);
 await page.locator('#user_pass').fill(credentials.password);
 await page.locator('#wp-submit').click();
 await page.waitForURL(/wp-admin/);
 await page.goto('/wp-admin/admin.php?page=creator-lms');
 await page.waitForLoadState('networkidle');
 await page.screenshot({path:testInfo.outputPath('admin.png'),fullPage:true});
 const inventory=await page.evaluate(()=>({scripts:[...document.scripts].map(s=>({id:s.id,src:s.src})).filter(s=>s.src),styles:[...document.querySelectorAll('link[rel=stylesheet]')].map(s=>({id:s.id,href:s.href})),globals:Object.keys(window).filter(k=>/^(wp$|React|jQuery|ohmylms|omlms|creator|webpack)/i.test(k)),resources:performance.getEntriesByType('resource').map(r=>({url:r.name,type:r.initiatorType}))}));
 await testInfo.attach('asset-inventory',{body:JSON.stringify(inventory,null,2),contentType:'application/json'});
 expect(inventory.scripts.some(s=>s.src.includes('/build/assets/dist/admin/creatorlms.js'))).toBe(true);
 await testInfo.attach('browser-observations',{body:JSON.stringify({errors,failures,links:await page.locator('a').evaluateAll(links=>links.map(a=>({text:a.textContent.trim(),href:a.getAttribute('href')})))},null,2),contentType:'application/json'});
 expect(await page.locator('body').innerText()).not.toContain('critical error');
 expect(errors).toEqual([]);
 expect(failures).toEqual([]);
});
